server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: patient-service
          uri: http://patient-service
          predicates:
            - Path=/patients, /patients/**
          filters:
            - RewritePath=/patients(?<segment>/?.*), /auth$\{segment}
        - id: doctor-service
          uri: http://doctor-service
          predicates:
            - Path=/doctors, /doctors/**
        - id: doctor-service-schedules
          uri: http://doctor-service
          predicates:
            - Path=/schedules, /schedules/**
        - id: appointment-service
          uri: http://appointment-service
          predicates:
            - Path=/appointments, /appointments/**
          filters:
            - RewritePath=/appointments(?<segment>/?.*), /slots$\{segment}
        - id: notification-service
          uri: http://notification-service
          predicates:
            - Path=/notifications, /notifications/**
          filters:
            - RewritePath=/notifications(?<segment>/?.*), /api/notifications$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
