server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: patient-service
          uri: http://patient-service:8081
          predicates:
            - Path=/patients/**
          filters:
            - RewritePath=/patients/(?<segment>.*), /auth/$\{segment}
        - id: doctor-service
          uri: http://doctor-service:8085
          predicates:
            - Path=/doctors/**
        - id: doctor-service-schedules
          uri: http://doctor-service:8085
          predicates:
            - Path=/schedules/**
        - id: appointment-service
          uri: http://appointment-service:8082
          predicates:
            - Path=/appointments/**
          filters:
            - RewritePath=/appointments/(?<segment>.*), /slots/$\{segment}
        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - Path=/notifications/**
          filters:
            - RewritePath=/notifications/(?<segment>.*), /api/notifications/$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
