# Metadata
spring.application.name=doctor-service
server.port=8085

# Database
spring.data.mongodb.uri=mongodb://localhost:27017/doctordb

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Service URLs
patient.service.url=http://localhost:8081
appointment.service.url=http://localhost:8082
notification.service.url=http://localhost:8083
