# Database Override
spring.data.mongodb.uri=mongodb://mongodb:27017/doctordb

# Service URL Overrides
patient.service.url=http://patient-service:8081
notification.service.url=http://notification-service:8083
appointment.service.url=http://appointment-service:8082