# Metadata
spring.application.name=patient-service
spring.cloud.config.enabled=false
server.port=8081

# Database
spring.data.mongodb.uri=mongodb://localhost:27017/userdb

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Service URLs
appointment.service.url=http://localhost:8082
notification.service.url=http://localhost:8083
doctor.service.url=http://localhost:8085
